# Generated by Django 4.0.5 on 2022-07-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=20)),
                ('current_file', models.IntegerField()),
                ('next_file', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='file_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_code', models.IntegerField()),
                ('store_file', models.FileField(max_length=300, upload_to='DOWNLOADED_FILES')),
                ('file_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.file_details')),
            ],
        ),
    ]
